#!/usr/bin/env python3

"""
TODO
"""

from os.path import dirname, isfile, join, realpath, relpath
from subprocess import run
from sys import argv, exit, stderr

repos = []
parent = realpath(".")
while True:
    f = join(parent, ".gitinv")
    if isfile(f):
        for l in open(f, encoding="utf-8"):
            d, s = l.split()
            r = relpath(join(parent, d))
            if r.startswith(".."):
                continue
            g = join(r, ".git", "config")
            repos.append((isfile(g), r, g, s))
        break
    if parent == "/":
        break
    parent = dirname(parent)
if not repos:
    exit()
for exists, repo, config, remote in repos:
    print("\033[1;32m✓\033[0m" if exists else "\033[1;31m✗\033[0m", repo, file=stderr)
    if len(argv) == 1:
        continue
    cmd = None
    if argv[1] == "clone":
        if exists:
            continue
        cmd = ["git", "clone", remote, repo]
    else:
        if not exists:
            continue
        cmd = ["git", "-C", repo] + argv[1:]
    if cmd:
        run(cmd)
