#!/bin/sh -e

export GIT_DIR="${HOME}/.local/share/hgit/local.git"
export GIT_WORK_TREE="${HOME}"

case "${1}"
in
    ('')
        cd "${HOME}"

        e="${GIT_DIR}/info/exclude"
        test ! -f "${e}" \
        && echo '*' >"${e}"

        a="${GIT_DIR}/info/add"
        test -f "${a}" \
        && while read -r l
        do git add -f "${l}"
        done <"${a}"

        d=$(git diff HEAD)
        test -n "${d}"

        printf '%s\n\nCommit? [y/N] ' "${d}"
        read -r r
        test "${r}" = 'y'

        git commit -a -m "$(git status -bs | grep -Ev '^#')"
        git push
        ;;
    (ls)
        git ls-tree -r HEAD --name-only
        ;;
    (tig)
        shift
        tig "${@}"
        ;;
    (*)
        git "${@}"
        ;;
esac
